from . import ph_sss_table
from . import ph_philhealth_config
from . import ph_hdmf_table
from . import ph_loan_type
from . import hr_employee_loan
from . import hr_employee_loan_payment
from . import ph_allowance_type
from . import ph_payslip_allowance_line
from . import ph_contract_allowance_line
from . import ph_overtime_type
from . import hr_contract
from . import hr_payroll_structure
from . import hr_payslip
